name: PR Feature Validation

on:
  push:
    branches:
      - 'feature/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-and-pr:
    name: Lint, Test & Auto-PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run Unit Tests
        run: go test -v -cover ./tests/unit/...

      - name: Create Pull Request to Develop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_EXISTS=$(gh pr list --head ${{ github.ref_name }} --base develop --state open --json number --jq 'length')
          if [ "$PR_EXISTS" -eq "0" ]; then
            gh pr create --base develop --head ${{ github.ref_name }} --title "feat: PR automático de ${{ github.ref_name }}" --body "PR gerado automaticamente após validação de testes na branch de feature."
          else
            echo "Pull Request já existe. Nenhuma ação necessária."
          fi
